language: minimal

addons:
  ssh_known_hosts: $SERVER

before_script:
  - scp -o "StrictHostKeyChecking=no" variables install.sh $USUARIO@$SERVER:/home/$USUARIO << $PASSWD
script:
  - ssh -o "StrictHostKeyChecking=no" $USUARIO@$SERVER "sudo ./install.sh" << $PASSWD
