language: minimal

addons:
  ssh_known_hosts: $SERVER

before_script:
  - eval $(ssh-agent)
  - ssh-add crauss
  - scp -o "StrictHostKeyChecking=no" variables install.sh $USUARIO@$SERVER:/home/$USUARIO
script:
  - ssh -o "StrictHostKeyChecking=no" $USUARIO@$SERVER "sudo ./install.sh"
