language: minimal

addons:
  ssh_known_hosts: $SERVER

before_script:
  - scp variables install.sh $USUARIO@$SERVER:/home/$USUARIO << $PASSWD
script:
  - ssh $USUARIO@$SERVER "sudo ./install.sh" << $PASSWD
