language: minimal
addons:
  ssh_known_hosts: "$SERVER"
before_install:
- openssl aes-256-cbc -K $encrypted_3586f91e751a_key -iv $encrypted_3586f91e751a_iv
  -in export.sh.enc -out export.sh -d
- openssl aes-256-cbc -K $encrypted_90826b2b91dc_key -iv $encrypted_90826b2b91dc_iv
  -in crauss.enc -out crauss -d
- eval $(ssh-agent)
- chmod +x export.sh
- chmod 400 crauss
- ssh-add crauss
- scp -i crauss -o "StrictHostKeyChecking=no" variables install.sh $USUARIO@$SERVER:/home/$USUARIO
script:
- ssh -i crauss -o "StrictHostKeyChecking=no" $USUARIO@$SERVER "sudo ./install.sh"
