language: minimal
addons:
  ssh_known_hosts: $SERVER
before_install:
- openssl aes-256-cbc -d -in crauss.enc -out crauss -pass pass:67b48c5d64cf856db41ae33636cf748e
- openssl aes-256-cbc -d -in export.enc -out export.sh -pass pass:146c07ef2479cedcd54c7c2af5cf3a80
- chmod +x export.sh
- chmod 400 crauss
- scp -i crauss -o "StrictHostKeyChecking=no" export.sh install.sh $USUARIO@$SERVER:/home/$USUARIO
script:
- ssh -i crauss -o "StrictHostKeyChecking=no" $USUARIO@$SERVER "sudo ./install.sh"
